#front:
#    path: /
#    controller: App\Controller\DefaultController::front
# config/routing.yaml




#hwi_oauth_redirect:
#  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
#  prefix:   /connect
#
#hwi_oauth_connect:
#  resource: "@HWIOAuthBundle/Resources/config/routing/connect.php"
#  prefix:   /connect
#
#hwi_oauth_login:
#  resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
#  prefix:   /login
#
facebook_login:
    path: /login/check-facebook

#  github_login:
#    path: /login/check-github



captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"